#!/bin/bash

# This script creates a drupal project using Composer, initializes git with a
# first commit, installs the site using mysql and runs PHP's built-in http
# server at localhost:8888.
#
# PARAMETERS
# It uses the first parameter as the project folder name and database name.
# It uses the second optional parameter to set the site name, otherwise it uses
# the folder name.

PROJECT="$1"

if [ "$2" != "" ]; then
    SITE_NAME="$2"
else
    SITE_NAME="$2"
fi

# Set your local mysql user and password.
DB_USER="root"
DB_PASSWORD=""

set -x
# Create drupal project using composer.
composer create-project drupal-composer/drupal-project:8.x-dev $PROJECT --stability dev --no-interaction

cd $PROJECT

# Install the site using MySQL.
vendor/bin/drush site-install standard -y \
--db-url="mysql://$DB_USER:$DB_PASSWORD@localhost/$PROJECT" --account-pass=password --site-name="$SITE_NAME"

# Initialize git.
git init
git add .
git commit -m "Create drupal project using Composer"

# Run PHP's built-in http server at localhost:8888
vendor/bin/drush runserver
